server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: my-pic-comments
          group: my-pic
        output:
          destination: my-pic-comments
          group: my-pic