eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: my-pic-comments
          group: comments-service
          content-type: application/json
